src/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.cache import never_cache
from django.views.static import serve

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('product/', include('product.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, view=never_cache(serve))

src/product/urls.py
from django.urls import path
from django.views.generic import TemplateView

from product.views.product import CreateProductView, ProductList, SearchProduct, ProductCreateApiView
from product.views.variant import VariantView, VariantCreateView, VariantEditView

app_name = "product"

urlpatterns = [
    # Variants URLs
    path('variants/', VariantView.as_view(), name='variants'),
    path('variant/create', VariantCreateView.as_view(), name='create.variant'),
    path('variant/<int:id>/edit', VariantEditView.as_view(), name='update.variant'),

    # Products URLs
    path('create/', CreateProductView.as_view(), name='create.product'),
    # path('list/', TemplateView.as_view(template_name='products/list.html', extra_context={
    #     'product': True
    # }), name='list.product'),
    path('list/', ProductList, name="product-list"),
    path('search/', SearchProduct, name="product-search"),
    path('api/create/', ProductCreateApiView.as_view(), name="create-api")
]

src/product/models.py
from django.db import models
from config.g_model import TimeStampMixin


# Create your models here.
class Variant(TimeStampMixin):
    title = models.CharField(max_length=40, unique=True)
    description = models.TextField()
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.title


class Product(TimeStampMixin):
    title = models.CharField(max_length=255)
    sku = models.SlugField(max_length=255, unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class ProductImage(TimeStampMixin):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    file_path = models.URLField()

    def __str__(self):
        return self.product.title


class ProductVariant(TimeStampMixin):
    variant_title = models.CharField(max_length=255)
    variant = models.ForeignKey(Variant, on_delete=models.CASCADE, related_name="variantProduct")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="productVariant")

    def __str__(self):
        return self.variant_title


class ProductVariantPrice(TimeStampMixin):
    product_variant_one = models.ForeignKey(ProductVariant, on_delete=models.CASCADE, null=True,
                                            related_name='product_variant_one')
    product_variant_two = models.ForeignKey(ProductVariant, on_delete=models.CASCADE, null=True,
                                            related_name='product_variant_two')
    product_variant_three = models.ForeignKey(ProductVariant, on_delete=models.CASCADE, null=True,
                                              related_name='product_variant_three')
    price = models.FloatField()
    stock = models.FloatField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="productVariantPrice")

    def __str__(self):
        return self.product.title

src/product/forms.py
from django.forms import forms, ModelForm, CharField, TextInput, Textarea, BooleanField, CheckboxInput

from product.models import Variant


class VariantForm(ModelForm):
    class Meta:
        model = Variant
        fields = '__all__'
        widgets = {
            'title': TextInput(attrs={'class': 'form-control'}),
            'description': Textarea(attrs={'class': 'form-control'}),
            'active': CheckboxInput(attrs={'class': 'form-check-input', 'id': 'active'})
        }

src/product/views/product.py
from django.views import generic
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from rest_framework.views import APIView
from rest_framework.response import Response

from product.models import Variant, Product, ProductVariant


class ProductCreateApiView(APIView):

    def post(self, request):
        print(request.data)
        productName = request.data.get('productName')
        productSKU = request.data.get('productSKU')
        description = request.data.get('description')
        product = Product.objects.create(
            title=productName, sku=productSKU, description=description)
        productVariants = request.data.get('productVariants')
        for i in productVariants:
            # print(i)
            varient = Variant.objects.filter(id=i['option']).first()
            print(Variant.objects.filter(id=i['option']))
            for j in i['tags']:
                print(j)
                product_variant = ProductVariant.objects.create(
                    variant_title=j,
                    variant=varient,
                    product=product
                )

        # productVariantPrices = request.data.get('productVariantPrices')

        # product = Product.objects.create(
        #     title=productName, sku=productSKU, description=description)
        return Response("created")


def is_valid_queryparam(param):
    return param != '' and param is not None


class CreateProductView(generic.TemplateView):
    template_name = 'products/create.html'

    def get_context_data(self, **kwargs):
        context = super(CreateProductView, self).get_context_data(**kwargs)
        variants = Variant.objects.filter(active=True).values('id', 'title')
        print(self.request)
        context['product'] = True
        context['variants'] = list(variants.all())
        return context


def ProductList(request):
    products = Product.objects.all()
    # variant = Variant.objects.all().distinct('variantProduct__variant_title')
    # variant = Variant.objects.all().values_list(
    #     'variantProduct__variant_title', flat=True).distinct()
    variant = Variant.objects.all()

    paginator = Paginator(products, 4)
    page = request.GET.get('page', 1)
    paged_listings = paginator.get_page(page)

    context = {
        "products": paged_listings,
        "variant": variant,

    }
    return render(request, "products/list.html", context)


def SearchProduct(request):
    qs = Product.objects.all()
    variant = Variant.objects.all()

    title_contains_query = request.GET.get('title')
    variant_contains_query = request.GET.get('variant')
    price_from = request.GET.get('price_from')
    price_to = request.GET.get('price_to')
    date = request.GET.get('date')

    if is_valid_queryparam(title_contains_query):
        qs = qs.filter(title__icontains=title_contains_query)

    if is_valid_queryparam(variant_contains_query):
        qs = qs.filter(productVariant__variant_title=variant_contains_query)

    if is_valid_queryparam(price_from):
        qs = qs.filter(productVariantPrice__price__gte=price_from)

    if is_valid_queryparam(price_to):
        qs = qs.filter(productVariantPrice__price__lt=price_to)

    if is_valid_queryparam(date):
        qs = qs.filter(created_at=date)

    context = {
        "products": qs.distinct(),
        "variant": variant
    }
    return render(request, "products/list.html", context)


def EditProducts(request, pk):
    return render(request, "products/list.html")

src/product/views/variant.py
from django.views import generic
from django.views.generic import ListView, CreateView, UpdateView

from product.forms import VariantForm
from product.models import Variant


class BaseVariantView(generic.View):
    form_class = VariantForm
    model = Variant
    template_name = 'variants/create.html'
    success_url = '/product/variants'


class VariantView(BaseVariantView, ListView):
    template_name = 'variants/list.html'
    paginate_by = 10

    def get_queryset(self):
        filter_string = {}
        print(self.request.GET)
        for key in self.request.GET:
            if self.request.GET.get(key):
                filter_string[key] = self.request.GET.get(key)
        return Variant.objects.filter(**filter_string)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['product'] = True
        context['request'] = ''
        if self.request.GET:
            context['request'] = self.request.GET['title__icontains']
        return context


class VariantCreateView(BaseVariantView, CreateView):
    pass


class VariantEditView(BaseVariantView, UpdateView):
    pk_url_kwarg = 'id'

src/product/templates/products/create.html
{% extends 'backend/base.html' %}

{% block title %} Create Product {% endblock %}

{% block content %}
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Create Product</h1>
        <a href="{% url 'product:create.product' %}" class="float-right btn btn-primary">All Product</a>
    </div>


    <script>
    var varients = {{ variants|safe }}
    console.log(typeof varients)
    </script>

    <div id="root">
        <CreateProduct id="variants" data-variants="{{ variants|safe }}"></CreateProduct>
    </div>

{% endblock %}

src/product/templates/products/list.html
{% extends 'backend/base.html' %}

{% block title %} Product List {% endblock %}

{% block content %}

    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Products</h1>
    </div>


    <div class="card">
        <form action="{% url 'product:product-search' %}" method="get" class="card-header">
            <div class="form-row justify-content-between">
                <div class="col-md-2">
                    <input type="text" name="title" placeholder="Product Title" class="form-control">
                </div>
                <div class="col-md-2">
                    
                    <select name="variant" id="" class="form-control">
                        {% for v in variant %}
                        <option selected disabled>--Select A {{ v.title }}--</option>
                        {% for i in v.variantProduct.all  %}

                         <option value="{{ i.variant_title }}" >{{ i.variant_title }}</option>
                         
                         
                        {% endfor %}
                        {% endfor %}
                    </select>
                    
                </div>

                <div class="col-md-3">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">Price Range</span>
                        </div>
                        <input type="text" name="price_from" aria-label="First name" placeholder="From"
                               class="form-control">
                        <input type="text" name="price_to" aria-label="Last name" placeholder="To" class="form-control">
                    </div>
                </div>
                <div class="col-md-2">
                    <input type="date" name="date" placeholder="Date" class="form-control">
                </div>
                <div class="col-md-1">
                    <button type="submit" class="btn btn-primary float-right"><i class="fa fa-search"></i></button>
                </div>
            </div>
        </form>

        <div class="card-body">
            <div class="table-response">
                <table class="table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Variant</th>
                        <th width="150px">Action</th>
                    </tr>
                    </thead>

                    <tbody>
                        {% for product in products %}
                    <tr>
                        <td>{{ product.pk }}</td>
                        <td>{{ product.title }}<br> Created at : 25-Aug-2020</td>
                        <td>{{ product.description }}</td>
                        
                        <td>
                            
                            <dl class="row mb-0" style="height: 80px; overflow: hidden" id={{ product.pk }}>
                                {% for i in product.productVariantPrice.all %}
                                <dt class="col-sm-3 pb-0">
                                    {{ i.product_variant_one }}
                                    {{ i.product_variant_two }}
                                    {{ i.product_variant_three }}
                                </dt>
                                <dd class="col-sm-9">
                                    <dl class="row mb-0">
                                        <dd class="col-sm-4 pb-0">Price : {{ i.price }}</dd>
                                        <dd class="col-sm-8 pb-0">InStock : {{ i.stock }}.</dd>
                                    </dl>
                                </dd>
                                {% endfor %}

                            </dl>
                            
                            <button onclick="$('#{{ product.pk }}').toggleClass('h-auto')" class="btn btn-sm btn-link">Show more
                            </button>
                        </td>
                        
                        <td>
                            <div class="btn-group btn-group-sm">
                                <a href="" class="btn btn-success">Edit</a>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>

                </table>
            </div>

        </div>

        <div class="card-footer">
            <div class="row justify-content-between">
                <div class="col-md-6">
                    
                    <p>Showing 1 to 10 out of 100</p>
                </div>
                <div class="col-md-2">
                    {% if products.has_other_pages %}
              <ul class="pagination">
                {% if products.has_previous %}
                    <li class="page-item">
                        <a href="?page={{ products.previous_page_number }}" class="page-link">&laquo;</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">&laquo;</a>
                    </li>
                {% endif %}

              {% for i in products.paginator.page_range %}
                {% if products.number == i %}
                  <li class="page-item active">
                      <a class="page-link">{{ i }}</a>
                  </li>
                    
                    {% else %}
                    
                    <li class="page-item">
                        <a href="?page={{ i }}" class="page-link">{{ i }}</a>
                    </li>
                    
                  {% endif %}
              {% endfor %}
                {% if products.has_next %}
                    <li class="page-item">
                        <a href="?page={{ products.next_page_number }}" class="page-link">&raquo;</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">&raquo;</a>
                    </li>
                {% endif %}
              </ul>
            {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}